objects/RX_ExIm_Status__c.object
<CustomObject>
    <fields>
        <fullName>Finished__c</fullName>
        <label>Finished</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>Values: Export, Export ALL, Import, Import ALL</description>
        <externalId>true</externalId>
        <label>ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>REVVY Export Import Status</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>RX_ExIm_Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REVVY Export Import Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RX_DeleteCustomObjectBatchable.cls
global class RX_DeleteCustomObjectBatchable implements Database.Batchable<sObject> {
	String query;
	Integer customObjectIndex = 0;
	Integer batchSize;
	list<RX_IOMetadataWrapper> ioMetaData = null;
	
	global RX_DeleteCustomObjectBatchable(list<RX_IOMetadataWrapper> ioMetaData, Integer index, Integer batchSize) {
		this.customObjectIndex = index;
		this.batchSize = batchSize;
		this.ioMetaData = ioMetaData;
		query = 'select id from ' + ioMetaData[customObjectIndex].Custom_Object_Name;
        system.debug(logginglevel.info, 'Query string: ' + query);
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		Database.delete(scope, true);
	}
	
	global void finish(Database.BatchableContext BC) {
		AsyncApexJob a = [Select Id, Status, NumberOfErrors, JobItemsProcessed,
        	TotalJobItems, CreatedBy.Email, ExtendedStatus
        	from AsyncApexJob where Id = :bc.getJobId()];        
        	system.debug('--------------------- finish');
	    if(a.Status == 'Completed') {
	    	system.debug('--------------------- Completed');
	    	if(customObjectIndex < ioMetaData.size()-1) {
		    	RX_DeleteCustomObjectBatchable exp = new RX_DeleteCustomObjectBatchable(ioMetaData, customObjectIndex+1, batchSize);
		    	Database.executeBatch(exp, batchSize);
		    } else{
		    	upsert new RX_ExIm_Status__c(Id__c='Delete ALL',Status__c='Completed', Finished__c=System.now()) ID__c;
		    }
			//	RX_ImportCustomObjectBatchable ioBatchable = new RX_ImportCustomObjectBatchable(currentIndex+1);
			//	Database.executeBatch(ioBatchable, 2);
			//}
		}
	}
	
}